# Generated by Django 3.1.6 on 2021-02-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210207_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='caption',
        ),
    ]
